task_post:
    path: /task/{name}
    controller: App\Controller\Task\CreateTaskPostController
    methods: [POST]

task_put:
    path: /task/update
    controller: App\Controller\Task\UpdateTaskController::index

stop:
    path: /stop/{taskDetailId}
    controller: App\Controller\Task\StopTaskController::index

list:
    path: /list
    controller: App\Controller\Task\ListAllTasksController::index