doctrine:
    dbal:
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_general_ci
                url: '%env(DATABASE_URL)%'
    orm:
      auto_generate_proxy_classes: '%kernel.debug%'
      default_entity_manager: default
      entity_managers:
        default:
          naming_strategy: doctrine.orm.naming_strategy.underscore
          auto_mapping: false
          connection: default
          mappings:
            App:
              is_bundle: false
              type: xml
              dir: '%kernel.project_dir%/src/Tasks/Infrastructure/Persistence/Doctrine'
              prefix: 'App\Domain'
              alias: App
